import com.lx862.jcm.buildtools.BuildTools

plugins {
	id 'fabric-loom' version '1.17.19'
}

final BuildTools buildTools = new BuildTools(minecraft_version)

version = "${rootProject.mod_version}+${rootProject.minecraft_version}"

loom {
	runConfigs.configureEach { ideConfigGenerated = true }
}

repositories {
	maven { url = "https://maven.terraformersmc.com/" }
	flatDir { dirs "${rootProject.projectDir}/../libs" }
}

dependencies {
	minecraft "com.mojang:minecraft:${minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${buildTools.dependencies.fabricLoader()}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${buildTools.dependencies.fabricApi()}"
	modCompileOnly "com.terraformersmc:modmenu:${buildTools.dependencies.modMenu()}"
	compileOnly files("${rootProject.projectDir}/../libs/MTR-fabric-4.0.5+1.21.11-compile.jar")
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
}

java {
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
	withSourcesJar()
}

jar {
	from("LICENSE") {
		rename { "${it}_${base.archivesName.get()}" }
	}
}
